#!/bin/bash
set -ef -o pipefail
# Inherit defaults from env variables for easy scripting

[ -z "$ENGINE" ] && ENGINE=davinci
[ -z "$TEMPERATURE"  ] && TEMPERATURE=0.5
[ -z "$FREQ_PENALTY" ] && FREQ_PENALTY=0
[ -z "$PRES_PENALTY" ] && PRES_PENALTY=0

POSITIONAL=()
while [[ $# -gt 0 ]]; do
key="$1"
case $key in
    -e|--engine)
    ENGINE="$2"
    shift # past argument
    shift # past value
    ;;
    -t|--temperature)
    TEMPERATURE="$2"
    shift # past argument
    shift # past value
    ;;
    -f|--freq-penalty)
    FREQ_PENALTY="$2"
    shift # past argument
    shift # past value
    ;;
    -p|--pres-penalty)
    PRES_PENALTY="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameter
[ -z "$2" ] && MAX_TOKENS=64 || MAX_TOKENS="$2"

# FIXME: Improve error handling
curl -sSL -N -G https://api.openai.com/v1/engines/${ENGINE}/completions/browser_stream \
  --data-urlencode prompt="$1" \
  --data-urlencode max_tokens="$MAX_TOKENS" \
  --data-urlencode frequency_penalty="$FREQ_PENALTY" \
  --data-urlencode presence_penalty="$PRES_PENALTY" \
  -H "Authorization: Bearer $OPENAI_KEY" | sed -l 's/^data: //' | grep --line-buffer -v '^\[DONE\]$' | jq -j --unbuffered '.choices[0].text' 
# Add trailing newline
echo
