#!/bin/bash

function help() {
    cat << EndOfHelp
Convert a file to OpenAI format, as a single line of a JSON lines file.
Concatenate multiple file into one, or use this tool to upload directly.
Usage:
  echo filename.txt | to-openai-file
  ls -1 myfolder | xargs -I _ -L1 sh -c "cat _ | to-openai-file"
EndOfHelp
    exit
}

[ "$1" == "-h" ] && help
[ "$1" == "--help" ] && help

jq -s -R -c '{ text: . }'
